#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
